// Code generated by protoc-gen-go. DO NOT EDIT.
// This file will be regenerated by protoc during Docker build
// Source: fleet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Robot state enumeration
type RobotState int32

const (
	RobotState_UNKNOWN  RobotState = 0
	RobotState_IDLE     RobotState = 1
	RobotState_MOVING   RobotState = 2
	RobotState_PAUSED   RobotState = 3
	RobotState_ERROR    RobotState = 4
	RobotState_CHARGING RobotState = 5
	RobotState_OFFLINE  RobotState = 6
)

func (x RobotState) Enum() *RobotState {
	p := new(RobotState)
	*p = x
	return p
}

func (x RobotState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RobotState) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_proto_enumTypes[0].Descriptor()
}

func (RobotState) Type() protoreflect.EnumType {
	return &file_fleet_proto_enumTypes[0]
}

func (x RobotState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// CommandType enumeration
type CommandType int32

const (
	CommandType_CMD_UNKNOWN  CommandType = 0
	CommandType_CMD_MOVE     CommandType = 1
	CommandType_CMD_STOP     CommandType = 2
	CommandType_CMD_PAUSE    CommandType = 3
	CommandType_CMD_RESUME   CommandType = 4
	CommandType_CMD_DOCK     CommandType = 5
	CommandType_CMD_UNDOCK   CommandType = 6
	CommandType_CMD_LOCALIZE CommandType = 7
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_fleet_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// MissionType enumeration
type MissionType int32

const (
	MissionType_MISSION_UNKNOWN   MissionType = 0
	MissionType_MISSION_TRANSPORT MissionType = 1
	MissionType_MISSION_PATROL    MissionType = 2
	MissionType_MISSION_CHARGE    MissionType = 3
	MissionType_MISSION_CUSTOM    MissionType = 4
)

func (x MissionType) Enum() *MissionType {
	p := new(MissionType)
	*p = x
	return p
}

func (x MissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_proto_enumTypes[2].Descriptor()
}

func (MissionType) Type() protoreflect.EnumType {
	return &file_fleet_proto_enumTypes[2]
}

func (x MissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// WaypointAction enumeration
type WaypointAction int32

const (
	WaypointAction_WP_PASS    WaypointAction = 0
	WaypointAction_WP_STOP    WaypointAction = 1
	WaypointAction_WP_PICKUP  WaypointAction = 2
	WaypointAction_WP_DROPOFF WaypointAction = 3
)

func (x WaypointAction) Enum() *WaypointAction {
	p := new(WaypointAction)
	*p = x
	return p
}

func (x WaypointAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WaypointAction) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_proto_enumTypes[3].Descriptor()
}

func (WaypointAction) Type() protoreflect.EnumType {
	return &file_fleet_proto_enumTypes[3]
}

func (x WaypointAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// MissionStatus enumeration
type MissionStatus int32

const (
	MissionStatus_MISSION_STATUS_UNKNOWN MissionStatus = 0
	MissionStatus_MISSION_PENDING        MissionStatus = 1
	MissionStatus_MISSION_IN_PROGRESS    MissionStatus = 2
	MissionStatus_MISSION_COMPLETED      MissionStatus = 3
	MissionStatus_MISSION_CANCELLED      MissionStatus = 4
	MissionStatus_MISSION_FAILED         MissionStatus = 5
)

func (x MissionStatus) Enum() *MissionStatus {
	p := new(MissionStatus)
	*p = x
	return p
}

func (x MissionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MissionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_fleet_proto_enumTypes[4].Descriptor()
}

func (MissionStatus) Type() protoreflect.EnumType {
	return &file_fleet_proto_enumTypes[4]
}

func (x MissionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Empty message
type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	return mi.MessageOf(x)
}

// RobotId message
type RobotId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RobotId) Reset() {
	*x = RobotId{}
}

func (x *RobotId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotId) ProtoMessage() {}

func (x *RobotId) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	return mi.MessageOf(x)
}

func (x *RobotId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// MissionId message
type MissionId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MissionId) Reset() {
	*x = MissionId{}
}

func (x *MissionId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionId) ProtoMessage() {}

func (x *MissionId) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	return mi.MessageOf(x)
}

func (x *MissionId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// StreamRequest message
type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotIds   []string `protobuf:"bytes,1,rep,name=robot_ids,json=robotIds,proto3" json:"robot_ids,omitempty"`
	IntervalMs int32    `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	return mi.MessageOf(x)
}

func (x *StreamRequest) GetRobotIds() []string {
	if x != nil {
		return x.RobotIds
	}
	return nil
}

func (x *StreamRequest) GetIntervalMs() int32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

// Position message
type Position struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X     float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y     float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Theta float64 `protobuf:"fixed64,3,opt,name=theta,proto3" json:"theta,omitempty"`
}

func (x *Position) Reset() {
	*x = Position{}
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	return mi.MessageOf(x)
}

func (x *Position) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Position) GetTheta() float64 {
	if x != nil {
		return x.Theta
	}
	return 0
}

// RobotStatus message
type RobotStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Vendor           string            `protobuf:"bytes,3,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Model            string            `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	State            RobotState        `protobuf:"varint,5,opt,name=state,proto3,enum=fleet.RobotState" json:"state,omitempty"`
	Position         *Position         `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	BatteryLevel     int32             `protobuf:"varint,7,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	CurrentMissionId string            `protobuf:"bytes,8,opt,name=current_mission_id,json=currentMissionId,proto3" json:"current_mission_id,omitempty"`
	LastSeen         int64             `protobuf:"varint,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Metadata         map[string]string `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *RobotStatus) Reset() {
	*x = RobotStatus{}
}

func (x *RobotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotStatus) ProtoMessage() {}

func (x *RobotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[5]
	return mi.MessageOf(x)
}

func (x *RobotStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RobotStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RobotStatus) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *RobotStatus) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *RobotStatus) GetState() RobotState {
	if x != nil {
		return x.State
	}
	return RobotState_UNKNOWN
}

func (x *RobotStatus) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *RobotStatus) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *RobotStatus) GetCurrentMissionId() string {
	if x != nil {
		return x.CurrentMissionId
	}
	return ""
}

func (x *RobotStatus) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

func (x *RobotStatus) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// RobotList message
type RobotList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Robots []*RobotStatus `protobuf:"bytes,1,rep,name=robots,proto3" json:"robots,omitempty"`
	Total  int32          `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *RobotList) Reset() {
	*x = RobotList{}
}

func (x *RobotList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotList) ProtoMessage() {}

func (x *RobotList) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[6]
	return mi.MessageOf(x)
}

func (x *RobotList) GetRobots() []*RobotStatus {
	if x != nil {
		return x.Robots
	}
	return nil
}

func (x *RobotList) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Command message
type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RobotId    string            `protobuf:"bytes,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Type       CommandType       `protobuf:"varint,2,opt,name=type,proto3,enum=fleet.CommandType" json:"type,omitempty"`
	Parameters map[string]string `protobuf:"bytes,3,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Command) Reset() {
	*x = Command{}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[7]
	return mi.MessageOf(x)
}

func (x *Command) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_CMD_UNKNOWN
}

func (x *Command) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// CommandResponse message
type CommandResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success   bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CommandId string `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
}

func (x *CommandResponse) Reset() {
	*x = CommandResponse{}
}

func (x *CommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResponse) ProtoMessage() {}

func (x *CommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[8]
	return mi.MessageOf(x)
}

func (x *CommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

// Waypoint message
type Waypoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Position    *Position      `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Action      WaypointAction `protobuf:"varint,3,opt,name=action,proto3,enum=fleet.WaypointAction" json:"action,omitempty"`
	WaitTimeSec int32          `protobuf:"varint,4,opt,name=wait_time_sec,json=waitTimeSec,proto3" json:"wait_time_sec,omitempty"`
}

func (x *Waypoint) Reset() {
	*x = Waypoint{}
}

func (x *Waypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Waypoint) ProtoMessage() {}

func (x *Waypoint) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[9]
	return mi.MessageOf(x)
}

func (x *Waypoint) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Waypoint) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Waypoint) GetAction() WaypointAction {
	if x != nil {
		return x.Action
	}
	return WaypointAction_WP_PASS
}

func (x *Waypoint) GetWaitTimeSec() int32 {
	if x != nil {
		return x.WaitTimeSec
	}
	return 0
}

// MissionRequest message
type MissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MissionId  string            `protobuf:"bytes,1,opt,name=mission_id,json=missionId,proto3" json:"mission_id,omitempty"`
	RobotId    string            `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	Type       MissionType       `protobuf:"varint,3,opt,name=type,proto3,enum=fleet.MissionType" json:"type,omitempty"`
	Waypoints  []*Waypoint       `protobuf:"bytes,4,rep,name=waypoints,proto3" json:"waypoints,omitempty"`
	Priority   int32             `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	Parameters map[string]string `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *MissionRequest) Reset() {
	*x = MissionRequest{}
}

func (x *MissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionRequest) ProtoMessage() {}

func (x *MissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[10]
	return mi.MessageOf(x)
}

func (x *MissionRequest) GetMissionId() string {
	if x != nil {
		return x.MissionId
	}
	return ""
}

func (x *MissionRequest) GetRobotId() string {
	if x != nil {
		return x.RobotId
	}
	return ""
}

func (x *MissionRequest) GetType() MissionType {
	if x != nil {
		return x.Type
	}
	return MissionType_MISSION_UNKNOWN
}

func (x *MissionRequest) GetWaypoints() []*Waypoint {
	if x != nil {
		return x.Waypoints
	}
	return nil
}

func (x *MissionRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MissionRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// MissionResponse message
type MissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool          `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status  MissionStatus `protobuf:"varint,3,opt,name=status,proto3,enum=fleet.MissionStatus" json:"status,omitempty"`
}

func (x *MissionResponse) Reset() {
	*x = MissionResponse{}
}

func (x *MissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MissionResponse) ProtoMessage() {}

func (x *MissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[11]
	return mi.MessageOf(x)
}

func (x *MissionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MissionResponse) GetStatus() MissionStatus {
	if x != nil {
		return x.Status
	}
	return MissionStatus_MISSION_STATUS_UNKNOWN
}

// HealthResponse message
type HealthResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Healthy         bool   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version         string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ConnectedRobots int32  `protobuf:"varint,3,opt,name=connected_robots,json=connectedRobots,proto3" json:"connected_robots,omitempty"`
	UptimeSeconds   int64  `protobuf:"varint,4,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[12]
	return mi.MessageOf(x)
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetConnectedRobots() int32 {
	if x != nil {
		return x.ConnectedRobots
	}
	return 0
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// File descriptor placeholders for compilation
var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_fleet_proto_enumTypes [5]struct {
	protoimpl.EnumInfo
}

func init() {
	file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
}

var _ = reflect.TypeOf
var _ = sync.Mutex{}
