// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// This file will be regenerated by protoc during Docker build
// Source: fleet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// FleetGatewayClient is the client API for FleetGateway service.
type FleetGatewayClient interface {
	// ロボット状態のストリーミング
	StreamRobotStatus(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (FleetGateway_StreamRobotStatusClient, error)
	// 全ロボット状態の取得
	GetAllRobots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RobotList, error)
	// 特定ロボットの状態取得
	GetRobot(ctx context.Context, in *RobotId, opts ...grpc.CallOption) (*RobotStatus, error)
	// ロボットへのコマンド送信
	SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResponse, error)
	// ミッションの開始
	StartMission(ctx context.Context, in *MissionRequest, opts ...grpc.CallOption) (*MissionResponse, error)
	// ミッションのキャンセル
	CancelMission(ctx context.Context, in *MissionId, opts ...grpc.CallOption) (*MissionResponse, error)
	// ヘルスチェック
	HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type fleetGatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetGatewayClient(cc grpc.ClientConnInterface) FleetGatewayClient {
	return &fleetGatewayClient{cc}
}

func (c *fleetGatewayClient) StreamRobotStatus(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (FleetGateway_StreamRobotStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &FleetGateway_ServiceDesc.Streams[0], "/fleet.FleetGateway/StreamRobotStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &fleetGatewayStreamRobotStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FleetGateway_StreamRobotStatusClient interface {
	Recv() (*RobotStatus, error)
	grpc.ClientStream
}

type fleetGatewayStreamRobotStatusClient struct {
	grpc.ClientStream
}

func (x *fleetGatewayStreamRobotStatusClient) Recv() (*RobotStatus, error) {
	m := new(RobotStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fleetGatewayClient) GetAllRobots(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RobotList, error) {
	out := new(RobotList)
	err := c.cc.Invoke(ctx, "/fleet.FleetGateway/GetAllRobots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetGatewayClient) GetRobot(ctx context.Context, in *RobotId, opts ...grpc.CallOption) (*RobotStatus, error) {
	out := new(RobotStatus)
	err := c.cc.Invoke(ctx, "/fleet.FleetGateway/GetRobot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetGatewayClient) SendCommand(ctx context.Context, in *Command, opts ...grpc.CallOption) (*CommandResponse, error) {
	out := new(CommandResponse)
	err := c.cc.Invoke(ctx, "/fleet.FleetGateway/SendCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetGatewayClient) StartMission(ctx context.Context, in *MissionRequest, opts ...grpc.CallOption) (*MissionResponse, error) {
	out := new(MissionResponse)
	err := c.cc.Invoke(ctx, "/fleet.FleetGateway/StartMission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetGatewayClient) CancelMission(ctx context.Context, in *MissionId, opts ...grpc.CallOption) (*MissionResponse, error) {
	out := new(MissionResponse)
	err := c.cc.Invoke(ctx, "/fleet.FleetGateway/CancelMission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetGatewayClient) HealthCheck(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, "/fleet.FleetGateway/HealthCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetGatewayServer is the server API for FleetGateway service.
type FleetGatewayServer interface {
	// ロボット状態のストリーミング
	StreamRobotStatus(*StreamRequest, FleetGateway_StreamRobotStatusServer) error
	// 全ロボット状態の取得
	GetAllRobots(context.Context, *Empty) (*RobotList, error)
	// 特定ロボットの状態取得
	GetRobot(context.Context, *RobotId) (*RobotStatus, error)
	// ロボットへのコマンド送信
	SendCommand(context.Context, *Command) (*CommandResponse, error)
	// ミッションの開始
	StartMission(context.Context, *MissionRequest) (*MissionResponse, error)
	// ミッションのキャンセル
	CancelMission(context.Context, *MissionId) (*MissionResponse, error)
	// ヘルスチェック
	HealthCheck(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedFleetGatewayServer()
}

// UnimplementedFleetGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedFleetGatewayServer struct{}

func (UnimplementedFleetGatewayServer) StreamRobotStatus(*StreamRequest, FleetGateway_StreamRobotStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamRobotStatus not implemented")
}
func (UnimplementedFleetGatewayServer) GetAllRobots(context.Context, *Empty) (*RobotList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRobots not implemented")
}
func (UnimplementedFleetGatewayServer) GetRobot(context.Context, *RobotId) (*RobotStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRobot not implemented")
}
func (UnimplementedFleetGatewayServer) SendCommand(context.Context, *Command) (*CommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedFleetGatewayServer) StartMission(context.Context, *MissionRequest) (*MissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMission not implemented")
}
func (UnimplementedFleetGatewayServer) CancelMission(context.Context, *MissionId) (*MissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMission not implemented")
}
func (UnimplementedFleetGatewayServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedFleetGatewayServer) mustEmbedUnimplementedFleetGatewayServer() {}

// UnsafeFleetGatewayServer may be embedded to opt out of forward compatibility for this service.
type UnsafeFleetGatewayServer interface {
	mustEmbedUnimplementedFleetGatewayServer()
}

type FleetGateway_StreamRobotStatusServer interface {
	Send(*RobotStatus) error
	grpc.ServerStream
}

type fleetGatewayStreamRobotStatusServer struct {
	grpc.ServerStream
}

func (x *fleetGatewayStreamRobotStatusServer) Send(m *RobotStatus) error {
	return x.ServerStream.SendMsg(m)
}

func RegisterFleetGatewayServer(s grpc.ServiceRegistrar, srv FleetGatewayServer) {
	s.RegisterService(&FleetGateway_ServiceDesc, srv)
}

func _FleetGateway_StreamRobotStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FleetGatewayServer).StreamRobotStatus(m, &fleetGatewayStreamRobotStatusServer{stream})
}

func _FleetGateway_GetAllRobots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetGatewayServer).GetAllRobots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleet.FleetGateway/GetAllRobots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetGatewayServer).GetAllRobots(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetGateway_GetRobot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RobotId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetGatewayServer).GetRobot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleet.FleetGateway/GetRobot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetGatewayServer).GetRobot(ctx, req.(*RobotId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetGateway_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetGatewayServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleet.FleetGateway/SendCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetGatewayServer).SendCommand(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetGateway_StartMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetGatewayServer).StartMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleet.FleetGateway/StartMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetGatewayServer).StartMission(ctx, req.(*MissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetGateway_CancelMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MissionId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetGatewayServer).CancelMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleet.FleetGateway/CancelMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetGatewayServer).CancelMission(ctx, req.(*MissionId))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetGateway_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetGatewayServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/fleet.FleetGateway/HealthCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetGatewayServer).HealthCheck(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// FleetGateway_ServiceDesc is the grpc.ServiceDesc for FleetGateway service.
var FleetGateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.FleetGateway",
	HandlerType: (*FleetGatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllRobots",
			Handler:    _FleetGateway_GetAllRobots_Handler,
		},
		{
			MethodName: "GetRobot",
			Handler:    _FleetGateway_GetRobot_Handler,
		},
		{
			MethodName: "SendCommand",
			Handler:    _FleetGateway_SendCommand_Handler,
		},
		{
			MethodName: "StartMission",
			Handler:    _FleetGateway_StartMission_Handler,
		},
		{
			MethodName: "CancelMission",
			Handler:    _FleetGateway_CancelMission_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _FleetGateway_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRobotStatus",
			Handler:       _FleetGateway_StreamRobotStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fleet.proto",
}
