"""initial_schema

Revision ID: e9724f8de6e8
Revises: 
Create Date: 2026-02-13 19:29:51.112299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9724f8de6e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('adapter_type', sa.String(length=100), nullable=False),
    sa.Column('state', sa.Enum('DISCONNECTED', 'CONNECTING', 'IDLE', 'MOVING', 'ERROR', 'EMERGENCY_STOPPED', name='robot_state', create_constraint=True), nullable=False),
    sa.Column('capabilities', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('connection_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_robots_state', 'robots', ['state'], unique=False)
    op.create_table('sensor_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('sensor_type', sa.Enum('LIDAR', 'CAMERA', 'IMU', 'ODOMETRY', 'BATTERY', 'GPS', 'POINT_CLOUD', 'JOINT_STATE', name='sensor_type', create_constraint=True), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    timescaledb_hypertable={'time_column_name': 'timestamp'}
    )
    op.create_index(op.f('ix_sensor_data_robot_id'), 'sensor_data', ['robot_id'], unique=False)
    op.create_index('ix_sensor_data_robot_type_time', 'sensor_data', ['robot_id', 'sensor_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_data_session_id'), 'sensor_data', ['session_id'], unique=False)
    op.create_index(op.f('ix_sensor_data_timestamp'), 'sensor_data', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='user_role', create_constraint=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'TOKEN_REFRESH', 'ROBOT_CONNECT', 'ROBOT_DISCONNECT', 'VELOCITY_COMMAND', 'NAVIGATION_START', 'NAVIGATION_CANCEL', 'ESTOP_ACTIVATE', 'ESTOP_RELEASE', 'OPERATION_LOCK_ACQUIRE', 'OPERATION_LOCK_RELEASE', 'RECORDING_START', 'RECORDING_STOP', 'DATASET_CREATE', 'DATASET_EXPORT', 'DATASET_DELETE', 'DOCUMENT_UPLOAD', 'DOCUMENT_DELETE', 'RAG_QUERY', 'USER_CREATE', 'USER_UPDATE', 'USER_DELETE', 'SETTINGS_CHANGE', name='audit_action', create_constraint=True), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index('ix_audit_logs_user_time', 'audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATING', 'READY', 'EXPORTING', 'ARCHIVED', 'ERROR', name='dataset_status', create_constraint=True), nullable=False),
    sa.Column('sensor_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('robot_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_datasets_owner', 'datasets', ['owner_id'], unique=False)
    op.create_index('ix_datasets_status', 'datasets', ['status'], unique=False)
    op.create_table('rag_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=1000), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rag_documents_owner', 'rag_documents', ['owner_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['rag_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_chunks_document', 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_embedding', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('recording_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('robot_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_recording_sessions_active', 'recording_sessions', ['robot_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_recording_sessions_robot_id'), 'recording_sessions', ['robot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recording_sessions_robot_id'), table_name='recording_sessions')
    op.drop_index('ix_recording_sessions_active', table_name='recording_sessions')
    op.drop_table('recording_sessions')
    op.drop_index('ix_document_chunks_embedding', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index('ix_document_chunks_document', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_rag_documents_owner', table_name='rag_documents')
    op.drop_table('rag_documents')
    op.drop_index('ix_datasets_status', table_name='datasets')
    op.drop_index('ix_datasets_owner', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('ix_audit_logs_user_time', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensor_data_timestamp'), table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_session_id'), table_name='sensor_data')
    op.drop_index('ix_sensor_data_robot_type_time', table_name='sensor_data')
    op.drop_index(op.f('ix_sensor_data_robot_id'), table_name='sensor_data')
    op.drop_table('sensor_data')
    op.drop_index('ix_robots_state', table_name='robots')
    op.drop_table('robots')
    # ### end Alembic commands ###
