"""
gRPC Client for Fleet Gateway communication

Proto files (fleet_pb2.py, fleet_pb2_grpc.py) are auto-generated by
grpcio-tools during Docker build from backend/proto/fleet.proto.
Do NOT commit hand-written stubs here.
"""

from .client import FleetGatewayClient, get_gateway_client, gateway_client_context

__all__ = [
    "FleetGatewayClient",
    "get_gateway_client",
    "gateway_client_context",
]
