# -*- coding: utf-8 -*-
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# This file will be regenerated by grpcio-tools during Docker build
# source: fleet.proto

import grpc

from . import fleet_pb2 as fleet__pb2


class FleetGatewayStub:
    """Fleet Gateway Service - Backend ↔ Gateway間の双方向通信を提供"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamRobotStatus = channel.unary_stream(
            '/fleet.FleetGateway/StreamRobotStatus',
            request_serializer=_serialize_stream_request,
            response_deserializer=_deserialize_robot_status,
        )
        self.GetAllRobots = channel.unary_unary(
            '/fleet.FleetGateway/GetAllRobots',
            request_serializer=_serialize_empty,
            response_deserializer=_deserialize_robot_list,
        )
        self.GetRobot = channel.unary_unary(
            '/fleet.FleetGateway/GetRobot',
            request_serializer=_serialize_robot_id,
            response_deserializer=_deserialize_robot_status,
        )
        self.SendCommand = channel.unary_unary(
            '/fleet.FleetGateway/SendCommand',
            request_serializer=_serialize_command,
            response_deserializer=_deserialize_command_response,
        )
        self.StartMission = channel.unary_unary(
            '/fleet.FleetGateway/StartMission',
            request_serializer=_serialize_mission_request,
            response_deserializer=_deserialize_mission_response,
        )
        self.CancelMission = channel.unary_unary(
            '/fleet.FleetGateway/CancelMission',
            request_serializer=_serialize_mission_id,
            response_deserializer=_deserialize_mission_response,
        )
        self.HealthCheck = channel.unary_unary(
            '/fleet.FleetGateway/HealthCheck',
            request_serializer=_serialize_empty,
            response_deserializer=_deserialize_health_response,
        )


# Serializers and deserializers (simplified - actual implementation uses protobuf)
def _serialize_empty(msg):
    return b''

def _serialize_stream_request(msg):
    import json
    return json.dumps({
        'robot_ids': msg.robot_ids,
        'interval_ms': msg.interval_ms
    }).encode()

def _serialize_robot_id(msg):
    import json
    return json.dumps({'id': msg.id}).encode()

def _serialize_mission_id(msg):
    import json
    return json.dumps({'id': msg.id}).encode()

def _serialize_command(msg):
    import json
    return json.dumps({
        'robot_id': msg.robot_id,
        'type': msg.type,
        'parameters': msg.parameters
    }).encode()

def _serialize_mission_request(msg):
    import json
    waypoints = []
    for wp in msg.waypoints:
        waypoints.append({
            'id': wp.id,
            'position': {'x': wp.position.x, 'y': wp.position.y, 'theta': wp.position.theta},
            'action': wp.action,
            'wait_time_sec': wp.wait_time_sec
        })
    return json.dumps({
        'mission_id': msg.mission_id,
        'robot_id': msg.robot_id,
        'type': msg.type,
        'waypoints': waypoints,
        'priority': msg.priority,
        'parameters': msg.parameters
    }).encode()

def _deserialize_robot_status(data):
    import json
    d = json.loads(data.decode())
    pos = fleet__pb2.Position(
        x=d.get('position', {}).get('x', 0),
        y=d.get('position', {}).get('y', 0),
        theta=d.get('position', {}).get('theta', 0)
    )
    return fleet__pb2.RobotStatus(
        id=d.get('id', ''),
        name=d.get('name', ''),
        vendor=d.get('vendor', ''),
        model=d.get('model', ''),
        state=d.get('state', 0),
        position=pos,
        battery_level=d.get('battery_level', 0),
        current_mission_id=d.get('current_mission_id', ''),
        last_seen=d.get('last_seen', 0),
        metadata=d.get('metadata', {})
    )

def _deserialize_robot_list(data):
    import json
    d = json.loads(data.decode())
    robots = []
    for r in d.get('robots', []):
        pos = fleet__pb2.Position(
            x=r.get('position', {}).get('x', 0),
            y=r.get('position', {}).get('y', 0),
            theta=r.get('position', {}).get('theta', 0)
        )
        robots.append(fleet__pb2.RobotStatus(
            id=r.get('id', ''),
            name=r.get('name', ''),
            vendor=r.get('vendor', ''),
            model=r.get('model', ''),
            state=r.get('state', 0),
            position=pos,
            battery_level=r.get('battery_level', 0),
            current_mission_id=r.get('current_mission_id', ''),
            last_seen=r.get('last_seen', 0),
            metadata=r.get('metadata', {})
        ))
    return fleet__pb2.RobotList(robots=robots, total=d.get('total', 0))

def _deserialize_command_response(data):
    import json
    d = json.loads(data.decode())
    return fleet__pb2.CommandResponse(
        success=d.get('success', False),
        message=d.get('message', ''),
        command_id=d.get('command_id', '')
    )

def _deserialize_mission_response(data):
    import json
    d = json.loads(data.decode())
    return fleet__pb2.MissionResponse(
        success=d.get('success', False),
        message=d.get('message', ''),
        status=d.get('status', 0)
    )

def _deserialize_health_response(data):
    import json
    d = json.loads(data.decode())
    return fleet__pb2.HealthResponse(
        healthy=d.get('healthy', False),
        version=d.get('version', ''),
        connected_robots=d.get('connected_robots', 0),
        uptime_seconds=d.get('uptime_seconds', 0)
    )
