# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# This file will be regenerated by grpcio-tools during Docker build
# source: fleet.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_sym_db = _symbol_database.Default()

# Enum definitions
class RobotState:
    UNKNOWN = 0
    IDLE = 1
    MOVING = 2
    PAUSED = 3
    ERROR = 4
    CHARGING = 5
    OFFLINE = 6

class CommandType:
    CMD_UNKNOWN = 0
    CMD_MOVE = 1
    CMD_STOP = 2
    CMD_PAUSE = 3
    CMD_RESUME = 4
    CMD_DOCK = 5
    CMD_UNDOCK = 6
    CMD_LOCALIZE = 7

class MissionType:
    MISSION_UNKNOWN = 0
    MISSION_TRANSPORT = 1
    MISSION_PATROL = 2
    MISSION_CHARGE = 3
    MISSION_CUSTOM = 4

class WaypointAction:
    WP_PASS = 0
    WP_STOP = 1
    WP_PICKUP = 2
    WP_DROPOFF = 3

class MissionStatus:
    MISSION_STATUS_UNKNOWN = 0
    MISSION_PENDING = 1
    MISSION_IN_PROGRESS = 2
    MISSION_COMPLETED = 3
    MISSION_CANCELLED = 4
    MISSION_FAILED = 5


# Message classes
class Empty:
    def __init__(self):
        pass

class RobotId:
    def __init__(self, id: str = ""):
        self.id = id

class MissionId:
    def __init__(self, id: str = ""):
        self.id = id

class StreamRequest:
    def __init__(self, robot_ids: list = None, interval_ms: int = 0):
        self.robot_ids = robot_ids or []
        self.interval_ms = interval_ms

class Position:
    def __init__(self, x: float = 0.0, y: float = 0.0, theta: float = 0.0):
        self.x = x
        self.y = y
        self.theta = theta

class RobotStatus:
    def __init__(
        self,
        id: str = "",
        name: str = "",
        vendor: str = "",
        model: str = "",
        state: int = 0,
        position: Position = None,
        battery_level: int = 0,
        current_mission_id: str = "",
        last_seen: int = 0,
        metadata: dict = None
    ):
        self.id = id
        self.name = name
        self.vendor = vendor
        self.model = model
        self.state = state
        self.position = position or Position()
        self.battery_level = battery_level
        self.current_mission_id = current_mission_id
        self.last_seen = last_seen
        self.metadata = metadata or {}

class RobotList:
    def __init__(self, robots: list = None, total: int = 0):
        self.robots = robots or []
        self.total = total

class Command:
    def __init__(
        self,
        robot_id: str = "",
        type: int = 0,
        parameters: dict = None
    ):
        self.robot_id = robot_id
        self.type = type
        self.parameters = parameters or {}

class CommandResponse:
    def __init__(
        self,
        success: bool = False,
        message: str = "",
        command_id: str = ""
    ):
        self.success = success
        self.message = message
        self.command_id = command_id

class Waypoint:
    def __init__(
        self,
        id: str = "",
        position: Position = None,
        action: int = 0,
        wait_time_sec: int = 0
    ):
        self.id = id
        self.position = position or Position()
        self.action = action
        self.wait_time_sec = wait_time_sec

class MissionRequest:
    def __init__(
        self,
        mission_id: str = "",
        robot_id: str = "",
        type: int = 0,
        waypoints: list = None,
        priority: int = 0,
        parameters: dict = None
    ):
        self.mission_id = mission_id
        self.robot_id = robot_id
        self.type = type
        self.waypoints = waypoints or []
        self.priority = priority
        self.parameters = parameters or {}

class MissionResponse:
    def __init__(
        self,
        success: bool = False,
        message: str = "",
        status: int = 0
    ):
        self.success = success
        self.message = message
        self.status = status

class HealthResponse:
    def __init__(
        self,
        healthy: bool = False,
        version: str = "",
        connected_robots: int = 0,
        uptime_seconds: int = 0
    ):
        self.healthy = healthy
        self.version = version
        self.connected_robots = connected_robots
        self.uptime_seconds = uptime_seconds
